### ISSUE TITLE
AttributeError: 'LockBatch' object has no attribute 'seed'

### ISSUE THREAD

**Issue by zmhammedi** [yudasong/briee#1]
When trying to create an environment via 
`env, eval_env = make_batch_env(args)`

I get the error:
`AttributeError: 'LockBatch' object has no attribute 'seed'`

It seems like the source of this error is that gym.Env does not have the attribute 'seed'.  Have you encountered this error before?

**Comment by yudasong** [comment]
Hi,

This had never occurred to me before. Do you mind letting me know the version of the gym package that you are using? My guess is that different versions may have other interfaces.

**Comment by zmhammedi** [comment]
The gym version I have installed is 0.26.2. Which one are you running?

**Comment by yudasong** [comment]
Hi,
We tested our codebase with gym==0.14.0. Please let me know if that solves the problem!

**Comment by zmhammedi** [comment]
Yes, using gym==0.14.0 has resolved the error. Thanks!
